In [80]:
import numpy as np

In [105]:
def unit_length(matrix):
    row_norm = np.linalg.norm(matrix, axis=2)
    new_matrix = matrix / row_norm[:, :, np.newaxis]
    return new_matrix

In [ ]:
def bert_score(sentence_embeddings, question_embeddings):
    sentence_embeddings = unit_length(sentence_embeddings)
    question_embeddings = unit_length(question_embeddings)
    similarity = sentence_embeddings@question_embeddings.T
    recall = similarity.max(axis=1).sum()/len(sentence_embeddings)
    precision = similarity.max(axis=0).sum()/len(question_embeddings)
    f1 = 2*recall*precision/(recall+precision)
    return f1

In [97]:
sentence_embeddings = np.array([
    [
        [1, 2, 3],
        [0, 2, 1],
        [3, 5, 3],
    ],
    [
        [1, 0, 3],
        [2, 1, 1],
        [1, 2, 1],
    ]
])
question_embeddings = np.array([
    [
        [1, 0, 3],
        [0, 2, 1],
        [3, 2, 0],
        [1, 0, 1],
        [1, 0, 3],
    ],
    [
        [1, 1, 3],
        [1, 2, 1],
        [3, 2, 1],
        [1, 1, 1],
        [1, 1, 3],
    ]
])

In [108]:
sentence_embeddings = unit_length(sentence_embeddings)
question_embeddings = unit_length(question_embeddings)

In [147]:
sentence_embeddings[0]@question_embeddings[1].T

array([[0.96698756, 0.87287156, 0.71428571, 0.9258201 , 0.96698756],
       [0.67419986, 0.91287093, 0.5976143 , 0.77459667, 0.67419986],
       [0.78166083, 0.99611649, 0.89665306, 0.968496  , 0.78166083]])

In [152]:
np.tensordot(sentence_embeddings[1], question_embeddings[1], axes=(1,1))

array([[0.95346259, 0.51639778, 0.50709255, 0.73029674, 0.95346259],
       [0.73854895, 0.83333333, 0.98198051, 0.94280904, 0.73854895],
       [0.73854895, 1.        , 0.87287156, 0.94280904, 0.73854895]])

In [151]:
np.tensordot(sentence_embeddings[0], question_embeddings[0], axes=(1,1))

array([[0.84515425, 0.83666003, 0.51887452, 0.75592895, 0.84515425],
       [0.42426407, 1.        , 0.49613894, 0.31622777, 0.42426407],
       [0.57869139, 0.88659264, 0.80361438, 0.64699664, 0.57869139]])

In [165]:
np.ones(3)

array([1., 1., 1.])

In [176]:
np.tensordot(sentence_embeddings, question_embeddings, axes=(2,2))

array([[0.84515425, 0.83666003, 0.51887452, 0.75592895, 0.84515425],
       [0.42426407, 1.        , 0.49613894, 0.31622777, 0.42426407],
       [0.57869139, 0.88659264, 0.80361438, 0.64699664, 0.57869139]])

In [125]:
sentence_embeddings

array([[[0.26726124, 0.53452248, 0.80178373],
        [0.        , 0.89442719, 0.4472136 ],
        [0.45749571, 0.76249285, 0.45749571]],

       [[0.31622777, 0.        , 0.9486833 ],
        [0.81649658, 0.40824829, 0.40824829],
        [0.40824829, 0.81649658, 0.40824829]]])

In [142]:
question_embeddings

array([[[0.31622777, 0.        , 0.9486833 ],
        [0.        , 0.89442719, 0.4472136 ],
        [0.83205029, 0.5547002 , 0.        ],
        [0.70710678, 0.        , 0.70710678],
        [0.31622777, 0.        , 0.9486833 ]],

       [[0.30151134, 0.30151134, 0.90453403],
        [0.40824829, 0.81649658, 0.40824829],
        [0.80178373, 0.53452248, 0.26726124],
        [0.57735027, 0.57735027, 0.57735027],
        [0.30151134, 0.30151134, 0.90453403]]])

In [ ]:
recall = similarity.max(axis=1).sum()/len(sentence_embeddings)
precision = similarity.max(axis=0).sum()/len(question_embeddings)
f1 = 2*recall*precision/(recall+precision)
f1