In [1]:
from models.SequenceLabeller_BERT import SequenceLabeller_BERT
from Preprocess import Preprocess
from Pipeline import Pipeline
from languages.English import English
import numpy as np

In [2]:
%env WANDB_PROJECT=nlp_course_project

env: WANDB_PROJECT=nlp_course_project


In [3]:
english = English()

preproccesor = Preprocess(english.tokenize, english.clean)
data = Pipeline().get_data(language=english.name, preproccesor=preproccesor)
train_data, validation_data = Pipeline().split_data(data)

sequence_labeller = SequenceLabeller_BERT('english')


Loading data...


Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForTokenClassification: ['vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_layer_norm.bias', 'vocab_transform.bias', 'vocab_transform.weight', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForTokenClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN t

In [4]:
X_train = sequence_labeller.extract_X(train_data, 'english')
X_val = sequence_labeller.extract_X(validation_data, 'english')

  0%|          | 0/6700 [00:00<?, ?ex/s]

  0%|          | 0/1676 [00:00<?, ?ex/s]

In [5]:
sequence_labeller.train(X_train, None)

The following columns in the training set don't have a corresponding argument in `DistilBertForTokenClassification.forward` and have been ignored: __index_level_0__. If __index_level_0__ are not expected by `DistilBertForTokenClassification.forward`,  you can safely ignore this message.
/opt/homebrew/lib/python3.9/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 6700
  Num Epochs = 6
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 1260
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


wandb: Currently logged in as: christian2903. Use `wandb login --relogin` to force relogin


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


  0%|          | 0/1260 [00:00<?, ?it/s]

You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


KeyboardInterrupt: 

In [ ]:
sequence_labeller.load('english')

In [ ]:
sequence_labeller.trainer.predict(X_val)

TypeError: predict() got an unexpected keyword argument 'num_beams'

In [ ]:
predictions, labels, _ = sequence_labeller.predict(X_val)

The following columns in the test set don't have a corresponding argument in `DistilBertForTokenClassification.forward` and have been ignored: __index_level_0__. If __index_level_0__ are not expected by `DistilBertForTokenClassification.forward`,  you can safely ignore this message.
***** Running Prediction *****
  Num examples = 1676
  Batch size = 8
100%|██████████| 210/210 [03:39<00:00,  1.05s/it]


In [ ]:
labels[0][60:90]

array([   2,    2,    2, -100,    2,    0,    1, -100,    2,    2,    2,
          2,    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
          2,    2,    2,    2, -100,    2,    2,    2])

In [ ]:
predictions[0][0:90]

array([[-1.4066725 ,  0.04681121,  1.6711994 ],
       [-1.6559919 , -0.7665309 ,  2.247646  ],
       [-1.4070613 , -0.3968357 ,  1.8948702 ],
       [-1.5151194 , -0.36353305,  1.802545  ],
       [-1.539261  , -0.21519892,  1.7441562 ],
       [-1.6199429 , -0.92685306,  2.5797818 ],
       [-1.2990706 , -0.8998302 ,  2.8136146 ],
       [-1.5571741 , -0.47417626,  2.104074  ],
       [-1.4006313 , -0.33877587,  1.8768241 ],
       [-1.0588235 , -0.20095252,  1.8902411 ],
       [-1.5574266 , -0.39251485,  2.06343   ],
       [-1.4644817 , -0.2046403 ,  1.9011796 ],
       [-1.4170473 ,  0.15223353,  2.1174772 ],
       [-1.5676014 , -0.17670856,  2.0036454 ],
       [-1.5302593 ,  0.05464991,  1.5824662 ],
       [-1.716334  , -0.8696026 ,  2.5786073 ],
       [-1.3025912 , -0.8425342 ,  2.813366  ],
       [-1.4927621 , -0.37366256,  1.8522924 ],
       [-1.4694422 , -0.37675232,  1.9320039 ],
       [-1.546652  , -0.00751432,  1.7096289 ],
       [-1.5776865 , -0.16795304,  1.867

In [ ]:
predictions2 = np.argmax(predictions, axis=2)
predictions2[60:90]

array([[2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       ...,
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])